RegisterCommand('skel', function (source, args)
    print("Triggering Server event for skel...")
    print(source)
    TriggerServerEvent("InjurySystem:getGameInjury", source)
end, false)

RegisterNetEvent("InjurySystem:retGameInjury")
AddEventHandler("InjurySystem:retGameInjury", function (source, json)
    print(json)
end)